<?php

/**
 * @file
 * Contains openideal_idea.module.
 */

use Drupal\config_pages\Entity\ConfigPages;
use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_form_alter().
 */
function openideal_idea_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!in_array($form_id, ['node_idea_edit_form', 'node_idea_form'])) {
    return;
  }

  // Get settings page for default challenge entity.
  $openideal_config = config_pages_config('openideal_configurations');
  if (
    !empty($openideal_config)
    && $openideal_config instanceof ConfigPages
    && $openideal_config->hasField('field_default_challenge')
  ) {
    // Get default challenge entity.
    $default_challenge = $openideal_config->field_default_challenge->entity;
  }

  if (
      !empty($default_challenge)
      && empty($form['field_challenge']['widget'][0]['target_id']['#default_value'])
  ) {
    // Set default value for challenge form element of the idea content type.
    $form['field_challenge']['widget'][0]['target_id']['#default_value'] = $default_challenge;
  }
}
