<?php

/**
 * @file
 * Contains openideal_challenge.module.
 */

use Drupal\Core\Form\FormStateInterface;

/**
 * Implements hook_cron().
 */
function openideal_challenge_cron() {
  // Processing open/close scheduling challenge nodes via cron.
  /** @var \Drupal\openideal_challenge\Service\OpenidealChallengeService $challenge_service */
  $challenge_service = \Drupal::service('openideal_challenge.challenge_service');
  $challenge_service->openChallenges();
  $challenge_service->closeChallenges();
}

/**
 * Implements hook_form_alter().
 */
function openideal_challenge_form_alter(&$form, FormStateInterface $form_state, $form_id) {
  if (!in_array($form_id, ['node_challenge_edit_form', 'node_challenge_form'])) {
    return;
  }

  // Added visibility states to open_on and close_on form elements.
  $form['field_open_on']['#states'] = [
    'visible' => [
      ':input[name="field_is_open[value]"]' => ['checked' => FALSE],
    ],
  ];

  $form['field_close_on']['#states'] = [
    'visible' => [
      ':input[name="field_is_open[value]"]' => ['checked' => TRUE],
    ],
  ];

  // Move open_on/close_on form elements to the sidebar of the form.
  $form['challenge_scheduling_options'] = [
    '#type' => 'details',
    '#title' => t('Challenge scheduling options'),
    '#group' => 'advanced',
  ];

  $form['challenge_scheduling_options'][] = $form['field_open_on'];
  $form['challenge_scheduling_options'][] = $form['field_close_on'];
  unset($form['field_open_on']);
  unset($form['field_close_on']);
}
